# Static dependency closure produced from the reviewed foundation pin. Every
# archive/object is validated by software-webgpu/prepare.py before configuring.
set(COSMO_SOFTWARE_WEBGPU_METADATA "" CACHE FILEPATH "Completed portable WGPU dependency manifest")
if(NOT EXISTS "${COSMO_SOFTWARE_WEBGPU_METADATA}")
    message(FATAL_ERROR "Missing static software WebGPU dependencies; run cosmopolitan/build.py")
endif()
file(READ "${COSMO_SOFTWARE_WEBGPU_METADATA}" _cosmo_wgpu_json)
string(JSON _cosmo_wgpu_static GET "${_cosmo_wgpu_json}" static)
if(NOT _cosmo_wgpu_static)
    message(FATAL_ERROR "The software WebGPU foundation must be statically linked")
endif()
function(cosmo_wgpu_array output field)
    string(JSON count LENGTH "${_cosmo_wgpu_json}" "${field}")
    set(result)
    if(count GREATER 0)
        math(EXPR last "${count} - 1")
        foreach(index RANGE 0 ${last})
            string(JSON value GET "${_cosmo_wgpu_json}" "${field}" ${index})
            list(APPEND result "${value}")
        endforeach()
    endif()
    set(${output} "${result}" PARENT_SCOPE)
endfunction()
cosmo_wgpu_array(_cosmo_wgpu_includes include_dirs)
cosmo_wgpu_array(_cosmo_wgpu_sources runtime_sources)
cosmo_wgpu_array(_cosmo_wgpu_shims runtime_objects)
cosmo_wgpu_array(_cosmo_wgpu_driver driver_link_args)
cosmo_wgpu_array(_cosmo_wgpu_options runtime_link_options)
string(JSON _cosmo_wgpu_archive GET "${_cosmo_wgpu_json}" wgpu_archive)
add_library(cosmo-software-webgpu STATIC ${_cosmo_wgpu_sources})
target_compile_options(cosmo-software-webgpu PRIVATE -fno-stack-protector)
target_include_directories(cosmo-software-webgpu PUBLIC ${_cosmo_wgpu_includes})
target_link_options(cosmo-software-webgpu INTERFACE ${_cosmo_wgpu_options})
# Explicit object inputs retain Rust std's runtime overrides before libcosmo.a.
# The driver closure preserves Mesa whole-archive and LLVM archive grouping.
target_link_libraries(cosmo-software-webgpu PUBLIC
    ${_cosmo_wgpu_shims} "${_cosmo_wgpu_archive}" ${_cosmo_wgpu_driver})
