#!/usr/bin/env python3
"""Stage only the pinned portable application and reviewed Vast harness files.

No downloads, model files, Git checkout, credentials, or arbitrary directory
COPY are permitted. The caller resolves ubuntu:24.04 to an immutable manifest
digest before invoking this script; Docker must use that same build argument.
"""

import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import shutil
import tempfile


HERE = Path(__file__).resolve().parent


def sha256(path):
    with path.open("rb") as stream:
        return hashlib.file_digest(stream, "sha256").hexdigest()


def record(path, relative):
    return {"path": relative, "bytes": path.stat().st_size, "sha256": sha256(path)}


def checked_file(root, item):
    relative = Path(item["path"])
    if relative.is_absolute() or ".." in relative.parts:
        raise RuntimeError("Unsafe pinned path")
    path = root / relative
    if path.is_symlink() or not path.is_file():
        raise RuntimeError(f"Missing regular pinned file: {path}")
    if path.stat().st_size != item["bytes"] or sha256(path) != item["sha256"]:
        raise RuntimeError(f"Pinned file differs: {path}")
    return path


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--artifact-dir", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--base-image", required=True,
                        help="Resolved ubuntu:24.04@sha256:... image manifest")
    args = parser.parse_args()
    if not re.fullmatch(r"ubuntu:24\.04@sha256:[0-9a-f]{64}", args.base_image):
        parser.error("--base-image must pin ubuntu:24.04 by SHA-256 digest")
    output = args.output.resolve()
    if ".out" not in output.parts:
        parser.error("--output must be an explicit .out build-context directory")
    if output.exists() or output.is_symlink():
        parser.error("--output already exists; use a fresh context directory")
    artifact = args.artifact_dir.resolve(strict=True)
    pin_path = HERE / "PIN.json"
    pin = json.loads(pin_path.read_text())
    if pin["schema"] != 1:
        raise RuntimeError("Unsupported pin schema")
    sources = []
    for item in pin["files"]:
        relative = Path(item["path"])
        if len(relative.parts) != 2 or relative.parts[0] != "artifact":
            raise RuntimeError("Only flat pinned artifact files can be staged")
        sources.append((checked_file(artifact, {**item, "path": relative.name}), item))
    build = json.loads((artifact / "BUILD.json").read_text())
    if build["source"]["commit"] != pin["source_commit"] or build["source"]["dirty"] is not False:
        raise RuntimeError("Package does not identify the pinned clean source")
    if build["executable"] != {"filename": Path(pin["application"]["path"]).name,
                               "bytes": pin["application"]["bytes"],
                               "sha256": pin["application"]["sha256"]}:
        raise RuntimeError("Package manifest disagrees with application pin")
    if json.loads((artifact / "PIN.json").read_text()) != pin["model"]:
        raise RuntimeError("Packaged model pin differs from Vast model pin")
    # Validate every input before any context is published. Only these three
    # current-review files supplement the immutable application package.
    for name in ("Dockerfile", "prepare_helper.py", "run_test.py"):
        if not (HERE / name).is_file() or (HERE / name).is_symlink():
            raise RuntimeError(f"Missing reviewed context file: {name}")
    output.parent.mkdir(parents=True, exist_ok=True)
    staging = Path(tempfile.mkdtemp(prefix="context-", dir=output.parent))
    try:
        payload_dir = staging / "payload"
        (payload_dir / "artifact").mkdir(parents=True)
        for source, item in sources:
            target = payload_dir / item["path"]
            shutil.copy2(source, target)
            target.chmod(0o755 if target.name in ("easy-diffusion.exe", "ape-x86_64.elf") else 0o644)
            checked_file(payload_dir, item)
        shutil.copy2(pin_path, payload_dir / "PACKAGE_PIN.json")
        manifest = {"schema": 1, "source_commit": pin["source_commit"],
                    "run_id": pin["run_id"], "base_image": args.base_image,
                    "application": pin["application"], "loader": pin["loader"],
                    "files": pin["files"],
                    "package_pin": record(payload_dir / "PACKAGE_PIN.json", "PACKAGE_PIN.json"),
                    "helper_attestation_scope": "The native helper is generated by this Docker build; its recorded digest is build-output integrity, not an independent signature."}
        for name in ("Dockerfile", "prepare_helper.py", "run_test.py"):
            shutil.copy2(HERE / name, staging / name)
        manifest["harness_sources"] = [record(staging / name, name)
                                       for name in ("Dockerfile", "prepare_helper.py", "run_test.py")]
        (payload_dir / "PAYLOAD.json").write_text(json.dumps(manifest, indent=2) + "\n")
        (staging / "BASE_IMAGE.txt").write_text(args.base_image + "\n")
        (staging / ".dockerignore").write_text("*\n!Dockerfile\n!prepare_helper.py\n!run_test.py\n!payload/\n!payload/**\n")
        os.rename(staging, output)
    except BaseException:
        shutil.rmtree(staging)
        raise
    print(json.dumps({"status": "prepared", "context": str(output),
                      "base_image": args.base_image, "source_commit": pin["source_commit"],
                      "application_sha256": pin["application"]["sha256"]}, indent=2))


if __name__ == "__main__":
    main()
