#!/usr/bin/env python3
"""Prewarm Cosmopolitan 4.0.2's real native-loader helper during Docker build.

The helper is generated by the pinned application, not reconstructed here.
Keep both its executable and exact .c companion: libc/dlopen/dlopen.c accepts
matching source even when a later Docker COPY changes application timestamps.
https://github.com/jart/cosmopolitan/blob/4.0.2/libc/dlopen/dlopen.c
"""

import argparse
import hashlib
import json
import os
from pathlib import Path
import platform
import signal
import struct
import subprocess
import time


EXPECTED_SOURCE = "1730424270e35ff4a06bd978654c9990cfd5777e"
EXPECTED_APP = "7dd513293f53bc39bd7c92e3aaff0522c89f0d543c3390b4dd95e2f590b507b9"


def digest(path):
    with path.open("rb") as stream:
        return hashlib.file_digest(stream, "sha256").hexdigest()


def record(root, path, timestamps=False):
    result = {"path": path.relative_to(root).as_posix(), "bytes": path.stat().st_size,
              "sha256": digest(path)}
    if timestamps:
        result["mtime_ns"] = path.stat().st_mtime_ns
    return result


def verify_file(root, entry):
    relative = Path(entry["path"])
    if relative.is_absolute() or ".." in relative.parts:
        raise RuntimeError("Unsafe payload path")
    path = root / relative
    if path.is_symlink() or not path.is_file():
        raise RuntimeError(f"Missing regular payload file: {path}")
    actual = record(root, path)
    if any(actual[key] != entry[key] for key in ("path", "bytes", "sha256")):
        raise RuntimeError(f"Payload changed: {path}")
    return path


def invoke(command, environment, directory, label, report):
    stdout_path, stderr_path = directory / (label + ".stdout.log"), directory / (label + ".stderr.log")
    started = time.monotonic()
    with stdout_path.open("xb") as stdout, stderr_path.open("xb") as stderr:
        process = subprocess.Popen(command, cwd=directory, env=environment,
                                   stdin=subprocess.DEVNULL, stdout=stdout, stderr=stderr,
                                   start_new_session=True)
        try:
            code = process.wait(timeout=90)
        except subprocess.TimeoutExpired:
            os.killpg(process.pid, signal.SIGKILL)
            process.wait()
            raise RuntimeError("Native-loader helper preparation timed out")
        finally:
            try:
                os.killpg(process.pid, signal.SIGKILL)
            except ProcessLookupError:
                pass
    result = {"label": label, "command": command, "returncode": code,
              "seconds": round(time.monotonic() - started, 6), "path": environment["PATH"],
              "stdout": record(directory.parent, stdout_path),
              "stderr": record(directory.parent, stderr_path)}
    report["commands"].append(result)
    text = stderr_path.read_text(errors="replace")
    if code != 0:
        raise RuntimeError(f"Native-loader discovery failed with exit {code}: {text[-2000:]}")
    if "WebGPU: Vulkan provider=native; library=libvulkan.so.1" not in text:
        raise RuntimeError("Actual native Vulkan loader path was not exercised")
    for failure in ("WebGPU: cannot open", "has no vkGetInstanceProcAddr",
                    "native Vulkan initialization must start", "Segmentation fault"):
        if failure in text:
            raise RuntimeError("Native-loader discovery reported failure: " + failure)
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--build-dir", required=True, type=Path)
    parser.add_argument("--base-image", required=True)
    args = parser.parse_args()
    if platform.system() != "Linux" or platform.machine().lower() not in ("x86_64", "amd64"):
        raise RuntimeError("Helper preparation requires Linux x86_64")
    root = args.build_dir.resolve(strict=True)
    manifest_path = root / "PAYLOAD.json"
    manifest = json.loads(manifest_path.read_text())
    pin_path = verify_file(root, manifest["package_pin"])
    pin = json.loads(pin_path.read_text())
    if manifest["source_commit"] != EXPECTED_SOURCE or pin["source_commit"] != EXPECTED_SOURCE:
        raise RuntimeError("Unexpected source commit")
    if manifest["application"]["sha256"] != EXPECTED_APP or manifest["files"] != pin["files"]:
        raise RuntimeError("Unexpected application or payload pins")
    if manifest["base_image"] != args.base_image or "@sha256:" not in args.base_image:
        raise RuntimeError("Docker base differs from the staged resolved manifest")
    for item in manifest["files"]:
        verify_file(root, item)
    app = verify_file(root, manifest["application"])
    loader = verify_file(root, manifest["loader"])
    logs = root / "helper-preparation"
    logs.mkdir()
    temporary = root / "native-tmp"
    temporary.mkdir()
    helper = temporary / ".cosmo" / "dlopen-helper"
    source = helper.with_suffix(".c")
    report = {"schema": 1, "status": "failed", "base_image": args.base_image,
              "source_commit": EXPECTED_SOURCE, "application_sha256_before": digest(app),
              "commands": [], "scope": "Native loader/helper cache preparation; no GPU availability or compute claim"}
    try:
        environment = {"PATH": "/usr/bin:/bin", "TMPDIR": str(temporary),
                       "LC_ALL": "C", "LANG": "C", "LP_NUM_THREADS": "2",
                       "COSMO_WGPU_TRACE": "1"}
        command = [str(loader), str(app), "devices", "--backend", "cpu",
                   "--provider", "native", "--config", str(logs / "prewarm-config.json")]
        invoke(command, environment, logs, "prepare", report)
        if not helper.is_file() or helper.is_symlink() or not source.is_file() or source.is_symlink():
            raise RuntimeError("Pinned application did not produce its native helper and source")
        with helper.open("rb") as stream:
            header = stream.read(64)
        if len(header) != 64 or header[:6] != b"\x7fELF\x02\x01" or struct.unpack_from("<H", header, 18)[0] != 62:
            raise RuntimeError("Native helper is not a Linux x86_64 ELF")
        if not os.access(helper, os.X_OK) or b"dlopen" not in source.read_bytes():
            raise RuntimeError("Native helper/source is incomplete")
        # OCI tar layers may retain only whole-second mtimes. Normalize before
        # attesting/retesting so save/load/COPY cannot invalidate our manifest.
        # Exact source equality also permits reuse if the app later gets a
        # newer mtime (the pinned SDK checks that before invoking a compiler).
        cache_time = int(time.time())
        os.utime(helper, (cache_time, cache_time))
        os.utime(source, (cache_time, cache_time))
        before = record(root, helper, True)
        before["source"] = record(root, source, True)
        # Re-use the exact helper on a second real native initialization with
        # no compiler resolvable, matching the paid test's child environment.
        environment["PATH"] = "/no-tools"
        invoke(command, environment, logs, "compiler-free-cache", report)
        after = record(root, helper, True)
        after["source"] = record(root, source, True)
        if before != after:
            raise RuntimeError("Compiler-free native initialization changed the helper cache")
        for item in manifest["files"]:
            verify_file(root, item)
        report["application_sha256_after"] = digest(app)
        report["native_helper"] = after
        report["status"] = "passed"
        manifest["native_helper"] = after
    finally:
        report_path = logs / "report.json"
        report_path.write_text(json.dumps(report, indent=2) + "\n")
    manifest["helper_preparation"] = record(root, report_path)
    replacement = manifest_path.with_suffix(".json.tmp")
    replacement.write_text(json.dumps(manifest, indent=2) + "\n")
    os.replace(replacement, manifest_path)
    print(json.dumps(report, indent=2))


if __name__ == "__main__":
    main()
