(function () {
    "use strict"

    const core = window.PerchancePluginCore
    if (!core || document.getElementById(`${core.ID_PREFIX}-image-panel`)) return

    function attach() {
        const host = core.ensureMainTab()
        if (!host) return false
        const settings = core.loadSettings()
        const panel = document.createElement("section")
        panel.id = `${core.ID_PREFIX}-image-panel`
        panel.className = "panel-box"
        panel.innerHTML = window.loadRequiredPluginHTML("/plugins/core/perchance_plugin/perchance-image.plugin.html")
        host.appendChild(panel)

        const prompt = core.element("image-prompt")
        const negative = core.element("negative-prompt")
        const shape = core.element("shape")
        const seed = core.element("seed")
        const guidance = core.element("guidance-scale")
        const amount = core.element("amount")
        const generate = core.element("image-button")
        prompt.value = settings.imagePrompt || ""
        negative.value = settings.negativePrompt || ""
        shape.value = settings.shape || "square"
        seed.value = settings.seed || "-1"
        guidance.value = settings.guidanceScale || "7"
        amount.value = settings.amount || "1"

        function save() {
            core.saveSettings({
                imagePrompt: prompt.value,
                negativePrompt: negative.value,
                shape: shape.value,
                seed: seed.value,
                guidanceScale: guidance.value,
                amount: amount.value,
            })
        }
        ;[prompt, negative, shape, seed, guidance, amount].forEach((field) => {
            field.addEventListener("input", save)
            field.addEventListener("change", save)
        })
        core.element("import-image-prompt").addEventListener("click", () => {
            prompt.value = document.getElementById("prompt")?.value || ""
            negative.value = document.getElementById("negative_prompt")?.value || ""
            save()
            core.setStatus("Imported positive and negative prompts from Easy Diffusion.")
        })
        core.element("export-image-prompt").addEventListener("click", () => {
            const easyPrompt = document.getElementById("prompt")
            const easyNegative = document.getElementById("negative_prompt")
            if (easyPrompt) {
                easyPrompt.value = prompt.value
                core.dispatchInput(easyPrompt)
            }
            if (easyNegative) {
                easyNegative.value = negative.value
                core.dispatchInput(easyNegative)
            }
            core.setStatus("Exported prompts to Easy Diffusion.")
        })
        generate.addEventListener("click", async () => {
            if (!prompt.value.trim()) {
                core.setStatus("Enter an image prompt first.")
                prompt.focus()
                return
            }
            if (!amount.reportValidity()) return
            generate.disabled = true
            save()
            const requestedAmount = Number.parseInt(amount.value, 10)
            core.setStatus(`Generating ${requestedAmount} image${requestedAmount === 1 ? "" : "s"} with Perchance…`)
            try {
                const data = await core.requestJson("/perchance/image", {
                    prompt: prompt.value.trim(),
                    negative_prompt: negative.value,
                    shape: shape.value,
                    seed: seed.value,
                    guidance_scale: guidance.value,
                    amount: requestedAmount,
                })
                const images = Array.isArray(data.images) ? data.images : [data]
                const grid = core.element("image-grid")
                grid.replaceChildren()
                images.forEach((item, index) => {
                    const card = document.createElement("figure")
                    card.style.cssText = "margin:0;min-width:0;"
                    const image = document.createElement("img")
                    image.alt = `Generated by Perchance (${index + 1} of ${images.length})`
                    image.loading = "lazy"
                    image.src = `${item.url}?t=${Date.now()}-${index}`
                    image.style.cssText = "display:block;width:100%;max-height:640px;object-fit:contain;border-radius:6px;"
                    const link = document.createElement("a")
                    link.href = item.url
                    link.target = "_blank"
                    link.rel = "noopener"
                    link.textContent = item.relative_path || item.path
                    link.style.cssText = "display:block;margin-top:6px;overflow-wrap:anywhere;font-size:11px;"
                    card.append(image, link)
                    grid.appendChild(card)
                })
                core.element("image-result").style.display = "block"
                core.setStatus(`${images.length} image${images.length === 1 ? "" : "s"} generated and saved.`)
            } catch (error) {
                core.setStatus(`Image generation failed: ${error.message}`)
            } finally {
                generate.disabled = false
            }
        })
        core.initializePanel(panel)
        return true
    }

    if (!attach()) {
        let attempts = 0
        const timer = setInterval(() => {
            attempts += 1
            if (attach() || attempts >= 60) clearInterval(timer)
        }, 500)
    }
})()
