/* SPDX-License-Identifier: MIT */
#ifndef COSMO_LLAMA_SERVICE_H
#define COSMO_LLAMA_SERVICE_H
#include <stddef.h>
#include <stdint.h>
#ifdef __cplusplus
extern "C" {
#define COSMO_LLAMA_NOEXCEPT noexcept
#else
#define COSMO_LLAMA_NOEXCEPT
#endif

/* Synchronous request on the application's serialized inference lane.
   Borrowed inputs/callback state must remain valid until the call returns.
   Defaults for NULL model/prompt/backend/device: embedded stories260K,
   "Once upon a time", CPU, auto. Bounds: 1..4096 tokens, 1..256 threads,
   1 MiB prompt, 32768 context tokens and 16 MiB generated text.
   Progress runs on the inference thread; cancellation can also be queried
   by CPU backend workers. Callbacks must be thread-safe, must not throw and
   must not reenter inference. Cancellation is cooperative, including model
   load/prefill; a running GPU dispatch finishes before the next check. */
struct cosmo_llama_request {
    const char *model_path;
    const char *prompt;
    const char *backend;
    const char *device;
    int max_tokens;
    int threads;
    int (*cancelled)(void *user);
    void (*progress)(void *user, int generated, int requested);
    void *user;
};

/* Zero-initialize before use; free before reuse, including on error.
   text contains generated bytes only (no echoed prompt), followed by NUL;
   use text_bytes for length. Cancellation retains partial text/token IDs.
   _state is private recovery state; callers must never inspect it. */
struct cosmo_llama_result {
    char *text;
    size_t text_bytes;
    int32_t *token_ids;
    int token_count;
    int prompt_tokens;
    int cancelled;
    char error[512];
    void *_state;
};

enum cosmo_llama_status {
    COSMO_LLAMA_OK = 0,
    COSMO_LLAMA_ERROR = 1,
    COSMO_LLAMA_INVALID = 2,
    COSMO_LLAMA_CANCELLED = 3
};

/* Returns the status above; no C++ exception crosses these C entry points.
   The application owns global backend lifetime: this service does not call
   llama_backend_free per request. It currently creates a model/context per
   request rather than promising a persistent model-context cache. */
int cosmo_llama_service_generate(const struct cosmo_llama_request *request,
                                struct cosmo_llama_result *result) COSMO_LLAMA_NOEXCEPT;
void cosmo_llama_result_free(struct cosmo_llama_result *result) COSMO_LLAMA_NOEXCEPT;

/* Internal C engine / C++ exception-guard seam. Not client entry points. */
int cosmo_llama_service_engine(const struct cosmo_llama_request *request,
                              struct cosmo_llama_result *result);
void cosmo_llama_service_cleanup(struct cosmo_llama_result *result);

#undef COSMO_LLAMA_NOEXCEPT
#ifdef __cplusplus
}
#endif
#endif
