const assert=require('node:assert/strict');
const fs=require('node:fs');

module.exports=async function checkWorkbench(context,page,requests){
    await page.waitForFunction(()=>window.CppTemplateManager&&window.CppImageTools&&window.CppWildcard);
    const done=()=>page.waitForFunction(()=>CppGeneration.state.images===0);
    await page.locator('#cpp-spell-tokenizer summary').click();
    await page.fill('#prompt','red cat, blue cat, red_cat');await page.check('#cpp-token-highlight');
    assert.equal(await page.locator('.cpp-token-duplicate').count(),2);
    await page.getByRole('button',{name:'Move red cat later',exact:true}).click();
    assert.equal(await page.inputValue('#prompt'),'blue cat, red cat, red_cat');
    await page.locator('.cpp-token').first().dispatchEvent('wheel',{altKey:true,deltaY:-1});
    assert.match(await page.inputValue('#prompt'),/^\(blue cat\)/);
    await page.fill('#cpp-tag-search','az');
    await page.waitForSelector('#cpp-tag-results button');
    assert.match(await page.locator('#cpp-tag-results').innerText(),/blue_eyes/);
    await page.locator('#cpp-tag-results button').first().click();assert.match(await page.inputValue('#prompt'),/blue eyes$/);
    await page.check('#cpp-token-safe');await page.fill('#cpp-tag-search','blue');
    await page.waitForFunction(()=>document.querySelector('#cpp-tag-status').textContent.includes('matching tags'));
    assert.ok(await page.locator('#cpp-tag-results button').count()>0);
    await page.locator('#cpp-toggle-spellcheck summary').click();await page.check('#cpp-enable-spellcheck');
    assert.equal(await page.getAttribute('#prompt','spellcheck'),'true');assert.equal(await page.getAttribute('#negative_prompt','spellcheck'),'true');
    await page.uncheck('#cpp-enable-spellcheck');assert.equal(await page.getAttribute('#prompt','spellcheck'),'false');

    await page.locator('#cpp-stig-text-to-prompt summary').click();
    await page.setInputFiles('#cpp-wildcard-file',{name:'wildcards.txt',mimeType:'text/plain',buffer:Buffer.from('alpha\r\nbeta\nalpha')});
    await page.waitForFunction(()=>document.querySelector('#cpp-wildcard-count').textContent==='3 prompts loaded.');
    await page.fill('#cpp-wildcard-before','prefix');await page.fill('#cpp-wildcard-after','suffix');
    await page.click('#cpp-wildcard-next');assert.equal(await page.inputValue('#prompt'),'prefix, beta, suffix');
    await page.click('#cpp-wildcard-last');assert.equal(await page.inputValue('#cpp-wildcard-select'),'2');
    let at=requests.length;await page.click('#cpp-wildcard-sequential');
    await page.waitForFunction(()=>document.querySelector('#cpp-workbench-status').textContent==='Completed 3 tasks.');await done();
    assert.deepEqual(requests.slice(at).map(request=>request.prompt),['prefix, alpha, suffix','prefix, beta, suffix','prefix, alpha, suffix']);

    await page.evaluate(()=>CppGeneration.enqueue({...CppGeneration.buildRequest(),use_lora_model:['test-lora','other-lora'],lora_alpha:[.2,.8],num_outputs:1}));await done();
    let card=page.locator('.cpp-generated-image').first();await card.hover();
    at=requests.length;await card.getByRole('button',{name:'LoRA +0.1',exact:true}).click();await done();
    assert.deepEqual(requests[at].lora_alpha,[.3,.9]);
    card=page.locator('.cpp-generated-image').first();await card.hover();at=requests.length;
    await card.getByRole('button',{name:'LoRA grid 0–1',exact:true}).click();
    await page.waitForFunction(()=>document.querySelector('#cpp-workbench-status').textContent==='Completed 11 tasks.');await done();
    assert.equal(requests.length-at,11);assert.deepEqual(requests.slice(at).map(request=>request.lora_alpha[0]),Array.from({length:11},(_,i)=>i/10));
    card=page.locator('.cpp-generated-image').first();
    await card.locator('img').first().evaluate(async image=>{
        const canvas=document.createElement('canvas');canvas.width=4;canvas.height=2;const ctx=canvas.getContext('2d');ctx.fillStyle='red';ctx.fillRect(0,0,2,2);ctx.fillStyle='blue';ctx.fillRect(2,0,2,2);image.src=canvas.toDataURL();await image.decode();
    });
    await card.hover();await card.getByRole('button',{name:'Rotate right',exact:true}).click();
    await page.waitForFunction(()=>document.querySelector('.cpp-generated-image img').naturalHeight===4);
    assert.equal(await card.locator('img').first().evaluate(image=>image.naturalWidth),2);
    await card.getByRole('button',{name:'Rotate left',exact:true}).click();
    await page.waitForFunction(()=>document.querySelector('.cpp-generated-image img').naturalWidth===4);
    await card.getByRole('button',{name:'Tile horizontally',exact:true}).click();
    await page.waitForFunction(()=>document.querySelector('.cpp-generated-image img').naturalWidth===8);
    await card.getByRole('button',{name:'Image information',exact:true}).click();
    assert.match(await page.locator('.cpp-workbench-dialog pre').innerText(),/test-lora/);await page.locator('.cpp-workbench-dialog').getByRole('button',{name:'Close',exact:true}).click();
    const downloads=[];const downloaded=download=>downloads.push(download);page.on('download',downloaded);
    await card.hover();await card.getByRole('button',{name:'Download image + metadata',exact:true}).click();
    for(let i=0;i<100&&downloads.length<2;i++)await new Promise(resolve=>setTimeout(resolve,20));
    assert.equal(downloads.length,2);
    const metadata=downloads.find(download=>download.suggestedFilename().endsWith('.json'));
    assert.deepEqual(JSON.parse(fs.readFileSync(await metadata.path(),'utf8')).use_lora_model,['test-lora','other-lora']);
    page.off('download',downloaded);
    await card.getByRole('button',{name:'Add to Storyteller',exact:true}).click();
    await page.waitForFunction(()=>document.querySelectorAll('#cpp-story-items figure').length===1);
    await page.click('#cpp-story-tab');assert.equal(await page.locator('.generate-columns').isVisible(),false);
    assert.equal(await page.locator('#cpp-story-items canvas').evaluate(canvas=>canvas.width),8);
    await page.click('#cpp-story-remove-all');assert.equal(await page.locator('#cpp-story-items figure').count(),0);
    await page.click('#cpp-generation-tab');assert.equal(await page.locator('.generate-columns').isVisible(),true);

    await card.hover();await card.getByRole('button',{name:'Use as img2img source',exact:true}).click();
    await page.waitForSelector('#cpp-img2img-source-preview',{state:'attached'});
    await page.locator('#cpp-stig-image-to-img2img > summary').click();
    assert.deepEqual(await page.locator('#cpp-stig-image-to-img2img input:invalid').evaluateAll(inputs=>inputs.map(input=>input.id)),[], 'Img2img default controls must be valid');
    await page.click('#cpp-img2img-zero');await page.fill('#cpp-img2img-count','3');await page.fill('#seed','42');
    await page.fill('#cpp-img2img-strength','.3');await page.fill('#cpp-img2img-strength-every','1');await page.fill('#cpp-img2img-strength-delta','.1');
    await page.fill('#cpp-img2img-seed-every','1');await page.fill('#cpp-img2img-seed-delta','2');
    await page.selectOption('#cpp-img2img-prompt-mode','sequential');await page.fill('#cpp-img2img-prompt-every','1');await page.fill('#cpp-img2img-delay','0');
    at=requests.length;await page.click('#cpp-img2img-start');
    await page.waitForFunction(()=>document.querySelector('#cpp-img2img-status').textContent==='Completed 3 generations.').catch(async error=>{console.error('IMG2IMG:',await page.locator('#cpp-img2img-status').innerText(),await page.locator('#cpp-workbench-status').innerText());throw error;});await done();
    assert.equal(requests.length-at,3);assert.deepEqual(requests.slice(at).map(request=>request.seed),[42,44,46]);
    assert.deepEqual(requests.slice(at).map(request=>request.prompt_strength),[.3,.4,.5]);
    assert.deepEqual(requests.slice(at).map(request=>request.prompt),['prefix, alpha, suffix','prefix, beta, suffix','prefix, alpha, suffix']);
    assert.ok(requests.slice(at).every(request=>request.init_image.startsWith('data:image/')));
    await page.click('#cpp-img2img-clear');

    const legacy={name:'Legacy reference',task:{numOutputsTotal:1,reqBody:{prompt:'legacy cat',negative_prompt:'blur',seed:17,use_stable_diffusion_model:'sd15',width:64,height:128,num_inference_steps:31,guidance_scale:7,num_outputs:1,output_format:'png',session_id:'old-session',use_lora_model:['test-lora','other-lora'],lora_alpha:[.2,.8]}},extra:'retain'};
    await page.evaluate(async record=>{
        const db=await new Promise((resolve,reject)=>{const open=indexedDB.open('EasyDiffusionSettingsDatabase',1);open.onsuccess=()=>resolve(open.result);open.onerror=()=>reject(open.error);});
        await new Promise((resolve,reject)=>{const tx=db.transaction('EasyDiffusionSettings','readwrite');tx.objectStore('EasyDiffusionSettings').put({id:'task templates',value:JSON.stringify([record])});tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});db.close();await CppTemplateManager.reload();
    },legacy);
    await page.locator('#cpp-template-manager summary').click();
    await page.locator('.cpp-template-entry').getByRole('button',{name:'Load / edit',exact:true}).click();
    assert.equal(JSON.parse(await page.inputValue('#cpp-template-request')).num_inference_steps,31);
    await page.check('#cpp-template-restore-seeds');await page.fill('#cpp-template-copies','2');at=requests.length;
    await page.locator('.cpp-template-entry').getByRole('button',{name:'Run template',exact:true}).click();
    await page.waitForFunction(()=>document.querySelector('#cpp-template-status').textContent==='Completed 2 template images.');await done();
    assert.deepEqual(requests.slice(at).map(request=>request.seed),[17,18]);assert.equal(requests[at].height,128);assert.notEqual(requests[at].session_id,'old-session');
    const exportWait=page.waitForEvent('download');await page.click('#cpp-template-export');const exported=await exportWait;
    const backup=JSON.parse(fs.readFileSync(await exported.path(),'utf8'));assert.deepEqual(backup,[legacy]);
    await page.setInputFiles('#cpp-template-import',{name:'import.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify([{...legacy,name:'Modern import'},legacy]))});
    await page.waitForFunction(()=>document.querySelector('#cpp-template-status').textContent==='Imported 1 templates; preserved 1 same-name templates.');
    assert.equal(await page.locator('.cpp-template-entry').count(),2);
    await page.setInputFiles('#cpp-template-import',{name:'bad.json',mimeType:'application/json',buffer:Buffer.from('[{"name":"broken"}]')});
    await page.waitForFunction(()=>document.querySelector('#cpp-template-status').textContent.startsWith('Import failed:'));
    assert.equal(await page.locator('.cpp-template-entry').count(),2);
    const modern=page.locator('.cpp-template-entry').filter({hasText:'Modern import'});
    await modern.getByRole('button',{name:'Load / edit',exact:true}).click();await page.fill('#cpp-template-name','Modern renamed');await page.click('#cpp-template-save');
    await page.waitForFunction(()=>document.querySelector('#cpp-template-status').textContent==='Saved Modern renamed.');
    const stored=await page.evaluate(async()=>{
        const db=await new Promise(resolve=>{const open=indexedDB.open('EasyDiffusionSettingsDatabase',1);open.onsuccess=()=>resolve(open.result);});
        const value=await new Promise(resolve=>{const req=db.transaction('EasyDiffusionSettings').objectStore('EasyDiffusionSettings').get('task templates');req.onsuccess=()=>resolve(JSON.parse(req.result.value));});db.close();return value;
    });
    assert.equal(stored.find(record=>record.name==='Modern renamed').extra,'retain');assert.deepEqual(stored.find(record=>record.name==='Legacy reference'),legacy);
    // A second modern tab reads the exact legacy-compatible database state.
    const other=await context.newPage();await other.goto('http://cpp-plugins.test/cpp-ui');await other.waitForFunction(()=>window.CppTemplateManager);
    assert.equal(await other.locator('.cpp-template-entry').count(),2);await other.close();
    await page.fill('#prompt','cat');
    console.log('PASS: eight workbench ports; merged aliases/SFW/token editing; wildcard duplicate-preserving batches; multi-LoRA shuttle/grid; rotate/tile/metadata; Storyteller; scheduled feedback with wildcard prompts; legacy-compatible template DB import/export/rename/preservation; browser spellcheck.');
};
