const assert = require("node:assert/strict");
const fs = require("node:fs");
const vm = require("node:vm");
const path = require("node:path");
const file = path.join(__dirname, "../ui/media/js/ip-adapter-compatibility.js");
assert.ok(fs.existsSync(file), "Shared IP-Adapter compatibility module is missing");
const sandbox = { window: {} };
vm.runInNewContext(fs.readFileSync(file, "utf8"), sandbox);
const api = sandbox.window.NativeIPAdapterCompatibility;
const adapter = api.adapter("renamed", ["ip_adapter_anima", "ip_adapter_embedding_768"]);
assert.equal(api.family("renamed", ["anima"]), "anima");
assert.equal(api.family("Anima/anima-base-v1.0", []), "anima");
assert.equal(api.family("flux", []), "unsupported");
assert.equal(api.family("SDXL/foo", []), "sdxl");
assert.equal(api.family("sd2/foo", ["sd_v2_base"]), "unsupported");
assert.equal(api.compatible("renamed", ["siglip2_base_patch16_512"], adapter), true);
assert.equal(api.compatible("clip", ["clip_hidden_768", "clip_projection_768"], adapter), false);
assert.equal(api.adapter("Anima/custom", []), null);
assert.equal(api.adapterForFamily(adapter, "anima"), true);
assert.equal(api.adapterForFamily(adapter, "sdxl"), false);
const sd15 = api.adapter("ip-adapter_sd15", []);
assert.equal(api.compatible("clip_h", [], sd15), true);
assert.equal(api.compatible("renamed", ["siglip2_base_patch16_512"], sd15), false);
console.log("Shared IP-Adapter compatibility checks passed");
