name: '101 - Vulkan API.cpp [RESERVED]'
on:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  reserved:
    runs-on: ubuntu-24.04
    steps:
      - run: echo 'Reserved index 101 for future Vulkan API.cpp compilation.'
